### ISSUE TITLE
ukrainian tranlate

### ISSUE THREAD

**Issue by cappelikan** [Zren/plasma-applets#111] opened 2017-10-31 18:11 UTC
[ukrainian.txt](https://github.com/Zren/plasma-applets/files/1431810/ukrainian.txt)

**Comment by Zren** [comment] 2017-10-31 19:51
Awesome, thanks for taking the time to translate.

I've commited your translations, but I'll be fixing a few of the errors (which might be caused by Poedit).

1) `%1`, `%2`, etc is used to substitute a variable (like a number).

```
#: ../contents/ui/ForecastGraph.qml:333
#, c-format
msgid "%1mm"
msgstr "мм"
```

In `"мм"`, you've removed the `%1` which means you won't get the number of millimeters, you'll just have `"мм"` (actually it breaks completely).

![](https://i.imgur.com/J6lcDeo.png)

![](https://i.imgur.com/6jkMNsP.png)

2) Also, you added spaces in weird places, like 

```
<b>'&lt;b&gt;'ddd'&lt;/b&gt;'</b>
<b> '& lt; b & gt;' ddd '& lt; / b & gt;' </ b>
```

which cause it to look like 

![](https://i.imgur.com/1c1Ooyu.png)

instead of 

![](https://i.imgur.com/NJejqAm.png)

Notice how the `&lt;` are replaced with `<` and the `&gt;` is replaced with a `>`? These are [ampersand codes](http://rabbit.eng.miami.edu/info/htmlchars.html) which let us use those symbols within HTML.

**Comment by Zren** [comment] 2017-10-31 21:07
I merged your translations from this issue here:

https://github.com/Zren/plasma-applets/commit/71dfa5956ecb2b8091150b94d18089e09622be9b

**Closed by Zren** 2017-10-31 21:07 UTC
