### ISSUE TITLE
Pin option

### ISSUE THREAD

**Issue by vmorenomarin** [Zren/plasma-applets#26] opened 2016-05-18 00:18 UTC
Is there way to add a option to pin the calendar like other widgets?

![screenshot_20160517_191718](https://cloud.githubusercontent.com/assets/13444664/15343633/03dffd0c-1c64-11e6-9694-c740dfffa4ed.png)

**Comment by Zren** [comment] 2016-05-18 20:48
Duplicate of #15

**Closed by Zren** 2016-05-18 20:48 UTC
Labels: duplicate
